TACRED_VALID_CONDITIONS = {
    "per:alternate_names": ["PERSON:PERSON", "PERSON:MISC"],
    "per:date_of_birth": ["PERSON:DATE"],
    "per:age": ["PERSON:NUMBER", "PERSON:DURATION"],
    "per:country_of_birth": ["PERSON:COUNTRY"],
    "per:stateorprovince_of_birth": ["PERSON:STATE_OR_PROVINCE"],
    "per:city_of_birth": ["PERSON:CITY"],
    "per:origin": ["PERSON:NATIONALITY", "PERSON:COUNTRY", "PERSON:LOCATION"],
    "per:date_of_death": ["PERSON:DATE"],
    "per:country_of_death": ["PERSON:COUNTRY"],
    "per:stateorprovince_of_death": ["PERSON:STATE_OR_PROVINCE"],
    "per:city_of_death": ["PERSON:CITY", "PERSON:LOCATION"],
    "per:cause_of_death": ["PERSON:CAUSE_OF_DEATH"],
    "per:countries_of_residence": ["PERSON:COUNTRY", "PERSON:NATIONALITY"],
    "per:stateorprovinces_of_residence": ["PERSON:STATE_OR_PROVINCE"],
    "per:cities_of_residence": ["PERSON:CITY", "PERSON:LOCATION"],
    "per:schools_attended": ["PERSON:ORGANIZATION"],
    "per:title": ["PERSON:TITLE"],
    "per:employee_of": ["PERSON:ORGANIZATION"],
    "per:religion": ["PERSON:RELIGION"],
    "per:spouse": ["PERSON:PERSON"],
    "per:parents": ["PERSON:PERSON"],
    "per:children": ["PERSON:PERSON"],
    "per:siblings": ["PERSON:PERSON"],
    "per:other_family": ["PERSON:PERSON"],
    "per:charges": ["PERSON:CRIMINAL_CHARGE"],
    "org:alternate_names": ["ORGANIZATION:ORGANIZATION", "ORGANIZATION:MISC"],
    "org:political/religious_affiliation": [
        "ORGANIZATION:RELIGION",
        "ORGANIZATION:IDEOLOGY",
    ],
    "org:top_members/employees": ["ORGANIZATION:PERSON"],
    "org:number_of_employees/members": ["ORGANIZATION:NUMBER"],
    "org:members": ["ORGANIZATION:ORGANIZATION", "ORGANIZATION:COUNTRY"],
    "org:member_of": [
        "ORGANIZATION:ORGANIZATION",
        "ORGANIZATION:COUNTRY",
        "ORGANIZATION:LOCATION",
        "ORGANIZATION:STATE_OR_PROVINCE",
    ],
    "org:subsidiaries": ["ORGANIZATION:ORGANIZATION", "ORGANIZATION:LOCATION"],
    "org:parents": ["ORGANIZATION:ORGANIZATION", "ORGANIZATION:COUNTRY"],
    "org:founded_by": ["ORGANIZATION:PERSON"],
    "org:founded": ["ORGANIZATION:DATE"],
    "org:dissolved": ["ORGANIZATION:DATE"],
    "org:country_of_headquarters": ["ORGANIZATION:COUNTRY"],
    "org:stateorprovince_of_headquarters": ["ORGANIZATION:STATE_OR_PROVINCE"],
    "org:city_of_headquarters": ["ORGANIZATION:CITY", "ORGANIZATION:LOCATION"],
    "org:shareholders": ["ORGANIZATION:PERSON", "ORGANIZATION:ORGANIZATION"],
    "org:website": ["ORGANIZATION:URL"],
}
TACRED_LABEL_TEMPLATES = {
    "no_relation": ["{subj} has no known relations to {obj}"],
    "per:stateorprovince_of_death": ["{subj} died in the state or province {obj}"],
    "per:title": ["{subj} is a {obj}"],
    "org:member_of": ["{subj} is the member of {obj}"],
    "per:other_family": ["{subj} is the other family member of {obj}"],
    "org:country_of_headquarters": ["{subj} has a headquarter in the country {obj}"],
    "org:parents": ["{subj} has the parent company {obj}"],
    "per:stateorprovince_of_birth": ["{subj} was born in the state or province {obj}"],
    "per:spouse": ["{subj} is the spouse of {obj}"],
    "per:origin": ["{subj} has the nationality {obj}"],
    "per:date_of_birth": ["{subj} has birthday on {obj}"],
    "per:schools_attended": ["{subj} studied in {obj}"],
    "org:members": ["{subj} has the member {obj}"],
    "org:founded": ["{subj} was founded in {obj}"],
    "per:stateorprovinces_of_residence": [
        "{subj} lives in the state or province {obj}"
    ],
    "per:date_of_death": ["{subj} died in the date {obj}"],
    "org:shareholders": ["{subj} has shares hold in {obj}"],
    "org:website": ["{subj} has the website {obj}"],
    "org:subsidiaries": ["{subj} owns {obj}"],
    "per:charges": ["{subj} is convicted of {obj}"],
    "org:dissolved": ["{subj} dissolved in {obj}"],
    "org:stateorprovince_of_headquarters": [
        "{subj} has a headquarter in the state or province {obj}"
    ],
    "per:country_of_birth": ["{subj} was born in the country {obj}"],
    "per:siblings": ["{subj} is the siblings of {obj}"],
    "org:top_members/employees": ["{subj} has the high level member {obj}"],
    "per:cause_of_death": ["{subj} died because of {obj}"],
    "per:alternate_names": ["{subj} has the alternate name {obj}"],
    "org:number_of_employees/members": ["{subj} has the number of employees {obj}"],
    "per:cities_of_residence": ["{subj} lives in the city {obj}"],
    "org:city_of_headquarters": ["{subj} has a headquarter in the city {obj}"],
    "per:children": ["{subj} is the parent of {obj}"],
    "per:employee_of": ["{subj} is the employee of {obj}"],
    "org:political/religious_affiliation": [
        "{subj} has political affiliation with {obj}"
    ],
    "per:parents": ["{subj} has the parent {obj}"],
    "per:city_of_birth": ["{subj} was born in the city {obj}"],
    "per:age": ["{subj} has the age {obj}"],
    "per:countries_of_residence": ["{subj} lives in the country {obj}"],
    "org:alternate_names": ["{subj} is also known as {obj}"],
    "per:religion": ["{subj} has the religion {obj}"],
    "per:city_of_death": ["{subj} died in the city {obj}"],
    "per:country_of_death": ["{subj} died in the country {obj}"],
    "org:founded_by": ["{subj} was founded by {obj}"],
}
RETACRED_VALID_CONDITIONS = {
    "per:identity": ["PERSON:PERSON"],
    "per:title": ["PERSON:TITLE"],
    "per:employee_of": [
        "PERSON:ORGANIZATION",
        "PERSON:CITY",
        "PERSON:STATE_OR_PROVINCE",
        "PERSON:COUNTRY",
        "PERSON:NATIONALITY",
        "PERSON:LOCATION",
    ],
    "org:top_members/employees": ["ORGANIZATION:PERSON"],
    "org:alternate_names": ["ORGANIZATION:ORGANIZATION"],
    "org:country_of_branch": [
        "ORGANIZATION:COUNTRY",
        "ORGANIZATION:LOCATION",
        "ORGANIZATION:STATE_OR_PROVINCE",
        "ORGANIZATION:CITY",
    ],
    "org:city_of_branch": [
        "ORGANIZATION:CITY",
        "ORGANIZATION:LOCATION",
        "ORGANIZATION:STATE_OR_PROVINCE",
        "ORGANIZATION:COUNTRY",
    ],
    "org:members": [
        "ORGANIZATION:ORGANIZATION",
        "ORGANIZATION:COUNTRY",
        "ORGANIZATION:LOCATION",
        "ORGANIZATION:CITY",
        "ORGANIZATION:STATE_OR_PROVINCE",
    ],
    "per:age": ["PERSON:NUMBER", "PERSON:DURATION", "PERSON:TITLE", "PERSON:DATE"],
    "org:member_of": ["ORGANIZATION:ORGANIZATION"],
    "org:stateorprovince_of_branch": [
        "ORGANIZATION:STATE_OR_PROVINCE",
        "ORGANIZATION:LOCATION",
        "ORGANIZATION:COUNTRY",
        "ORGANIZATION:CITY",
    ],
    "per:origin": [
        "PERSON:NATIONALITY",
        "PERSON:COUNTRY",
        "PERSON:CITY",
        "PERSON:LOCATION",
    ],
    "per:children": ["PERSON:PERSON"],
    "per:spouse": ["PERSON:PERSON"],
    "per:stateorprovinces_of_residence": [
        "PERSON:STATE_OR_PROVINCE",
        "PERSON:LOCATION",
        "PERSON:CITY",
    ],
    "per:siblings": ["PERSON:PERSON"],
    "per:countries_of_residence": [
        "PERSON:COUNTRY",
        "PERSON:NATIONALITY",
        "PERSON:LOCATION",
        "PERSON:CITY",
    ],
    "org:political/religious_affiliation": [
        "ORGANIZATION:IDEOLOGY",
        "ORGANIZATION:RELIGION",
    ],
    "per:cities_of_residence": [
        "PERSON:CITY",
        "PERSON:STATE_OR_PROVINCE",
        "PERSON:LOCATION",
        "PERSON:COUNTRY",
    ],
    "per:parents": ["PERSON:PERSON"],
    "per:date_of_death": ["PERSON:DATE", "PERSON:NUMBER", "PERSON:DURATION"],
    "per:schools_attended": ["PERSON:ORGANIZATION"],
    "per:city_of_death": [
        "PERSON:CITY",
        "PERSON:STATE_OR_PROVINCE",
        "PERSON:LOCATION",
        "PERSON:COUNTRY",
    ],
    "org:website": ["ORGANIZATION:URL", "ORGANIZATION:NUMBER"],
    "per:cause_of_death": [
        "PERSON:CAUSE_OF_DEATH",
        "PERSON:CRIMINAL_CHARGE",
        "PERSON:DATE",
        "PERSON:TITLE",
    ],
    "org:founded_by": ["ORGANIZATION:PERSON"],
    "per:other_family": ["PERSON:PERSON"],
    "org:shareholders": ["ORGANIZATION:PERSON", "ORGANIZATION:ORGANIZATION"],
    "per:city_of_birth": [
        "PERSON:CITY",
        "PERSON:LOCATION",
        "PERSON:NATIONALITY",
        "PERSON:STATE_OR_PROVINCE",
    ],
    "per:charges": ["PERSON:CAUSE_OF_DEATH", "PERSON:CRIMINAL_CHARGE", "PERSON:TITLE"],
    "org:founded": ["ORGANIZATION:DATE"],
    "per:religion": ["PERSON:RELIGION", "PERSON:TITLE"],
    "per:date_of_birth": ["PERSON:DATE", "PERSON:NUMBER", "PERSON:DURATION"],
    "per:stateorprovince_of_death": ["PERSON:STATE_OR_PROVINCE"],
    "org:number_of_employees/members": ["ORGANIZATION:NUMBER"],
    "per:stateorprovince_of_birth": [
        "PERSON:STATE_OR_PROVINCE",
        "PERSON:LOCATION",
        "PERSON:NATIONALITY",
    ],
    "per:country_of_birth": [
        "PERSON:COUNTRY",
        "PERSON:STATE_OR_PROVINCE",
        "PERSON:NATIONALITY",
    ],
    "org:dissolved": ["ORGANIZATION:DATE"],
    "per:country_of_death": ["PERSON:NATIONALITY", "PERSON:COUNTRY"],
}
RETACRED_LABEL_TEMPLATES = {
    "no_relation": ["{subj} has no known relations to {obj}"],
    "per:religion": ["{subj} has the religion {obj}"],
    "org:country_of_branch": ["{subj} has a branch in the country {obj}"],
    "org:stateorprovince_of_branch": [
        "{subj} has a branch in the state or province {obj}"
    ],
    "org:city_of_branch": ["{subj} has a branch in the city {obj}"],
    "org:shareholders": ["{subj} has shares hold in {obj}"],
    "org:top_members/employees": ["{subj} has the high level member {obj}"],
    "org:members": ["{subj} has the member {obj}"],
    "org:website": ["{subj} has the website {obj}"],
    "per:parents": ["{subj} has the parent {obj}"],
    "org:number_of_employees/members": ["{subj} has the number of employees {obj}"],
    "org:political/religious_affiliation": [
        "{subj} has political affiliation with {obj}"
    ],
    "per:age": ["{subj} has the age {obj}"],
    "per:origin": ["{subj} has the nationality {obj}"],
    "org:alternate_names": ["{subj} is also known as {obj}"],
    "per:other_family": ["{subj} is the other family member of {obj}"],
    "per:identity": [
        "{subj} is the identity/pronoun of {obj}",
        "{subj} and {obj} are the same person",
    ],
    # "per:identity": ["{subj} is the personal pronoun of {obj}", "{obj} is the personal pronoun of {subj}", "{subj} and {obj} are the same person"],
    # "per:identity": ["{subj} is the personal pronoun of {obj}", "{subj} and {obj} are the same person"],
    "per:siblings": ["{subj} is the siblings of {obj}"],
    "org:member_of": ["{subj} is the member of {obj}"],
    "per:children": ["{subj} is the parent of {obj}"],
    "per:employee_of": ["{subj} is the employee of {obj}"],
    "per:spouse": ["{subj} is the spouse of {obj}"],
    "org:dissolved": ["{subj} dissolved in {obj}"],
    "per:schools_attended": ["{subj} studied in {obj}"],
    "per:country_of_death": ["{subj} died in the country {obj}"],
    "per:stateorprovince_of_death": ["{subj} died in the state or province {obj}"],
    "per:city_of_death": ["{subj} died in the city {obj}"],
    "per:date_of_death": ["{subj} died in the date {obj}"],
    "per:cause_of_death": ["{subj} died because of {obj}"],
    "org:founded": ["{subj} was founded in {obj}"],
    "org:founded_by": ["{subj} was founded by {obj}"],
    "per:countries_of_residence": ["{subj} lives in the country {obj}"],
    "per:stateorprovinces_of_residence": [
        "{subj} lives in the state or province {obj}"
    ],
    "per:cities_of_residence": ["{subj} lives in the city {obj}"],
    "per:country_of_birth": ["{subj} was born in the country {obj}"],
    "per:stateorprovince_of_birth": ["{subj} was born in the state or province {obj}"],
    "per:city_of_birth": ["{subj} was born in the city {obj}"],
    "per:date_of_birth": ["{subj} has birthday on {obj}"],
    "per:charges": ["{subj} is convicted of {obj}"],
    "per:title": ["{subj} is a {obj}"],
}
